### ISSUE TITLE
✨FEAT. 메인페이지 컨테이너 생성

### ISSUE THREAD

**Issue by sengooooo** [SWOnCampus/Frontend#12]
# 📝 Preview
<img width="612" alt="image" src="https://github.com/user-attachments/assets/4f0716c2-4314-44f7-ba7c-f559ca3db29f">

# ✅ Todo
- [ ] 메인 컨테이너 제작
- [ ] 로딩 컨테이너 제작
- [ ] 리포팅 컨테이너 제작

# 📌 Remark
